// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my FlowZen profile",
  description: "Get the signed-in FlowZen user's profile (display name, avatar, member since).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name, avatar_url, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = {
      email: ctx.getUserEmail() ?? null,
      display_name: data?.display_name ?? null,
      avatar_url: data?.avatar_url ?? null,
      member_since: data?.created_at ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/update-display-name.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var update_display_name_default = defineTool2({
  name: "update_display_name",
  title: "Update my display name",
  description: "Set the display name on the signed-in FlowZen user's profile.",
  inputSchema: {
    display_name: z.string().trim().min(1).max(60).describe("New display name.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ display_name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data, error } = await supabase.from("profiles").upsert({ user_id: userId, display_name }, { onConflict: "user_id" }).select("display_name").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Display name set to "${data?.display_name ?? display_name}".` }],
      structuredContent: { display_name: data?.display_name ?? display_name }
    };
  }
});

// src/lib/mcp/tools/suggest-break-activity.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var MINDFUL_ACTIVITIES = [
  "Take 5 slow deep breaths. Inhale for 4 seconds, hold for 4, exhale for 4.",
  "Stretch your shoulders and neck gently. Roll your head in slow circles.",
  "Stand up and walk around for 30 seconds. Feel the ground beneath your feet.",
  "Drink some water. Hydration helps your brain stay sharp.",
  "Look away from the screen for 20 seconds. Focus on something far away.",
  "Close your eyes and listen to the sounds around you for 15 seconds.",
  "Do 5 gentle wrist and finger stretches to prevent tension.",
  "Take a moment to notice 3 things you're grateful for right now.",
  "Stand up and do 5 slow squats to get your blood flowing.",
  "Place your hands on your belly and take 3 deep belly breaths."
];
var suggest_break_activity_default = defineTool3({
  name: "suggest_break_activity",
  title: "Suggest a mindful break activity",
  description: "Suggest one or more short mindful break activities from FlowZen's library, for use between focus sessions.",
  inputSchema: {
    count: z2.number().int().min(1).max(5).default(1).describe("How many distinct activities to suggest (1-5).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: ({ count }) => {
    const n = Math.min(Math.max(count ?? 1, 1), 5);
    const pool = [...MINDFUL_ACTIVITIES].sort(() => Math.random() - 0.5).slice(0, n);
    return {
      content: [{ type: "text", text: pool.map((a, i) => `${i + 1}. ${a}`).join("\n") }],
      structuredContent: { activities: pool }
    };
  }
});

// src/lib/mcp/tools/plan-focus-session.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var plan_focus_session_default = defineTool4({
  name: "plan_focus_session",
  title: "Plan a focus session",
  description: "Build a FlowZen Pomodoro plan for a block of available time: how many focus/break cycles fit, and the total focused minutes.",
  inputSchema: {
    available_minutes: z3.number().int().min(5).max(600).describe("Total time available, in minutes."),
    focus_minutes: z3.number().int().min(5).max(120).default(25).describe("Length of each focus session."),
    break_minutes: z3.number().int().min(1).max(60).default(5).describe("Length of each break.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ available_minutes, focus_minutes, break_minutes }) => {
    const focus = focus_minutes ?? 25;
    const brk = break_minutes ?? 5;
    const cycle = focus + brk;
    let remaining = available_minutes;
    const schedule = [];
    let step = 1;
    while (remaining >= focus) {
      schedule.push({ step: step++, type: "focus", minutes: focus });
      remaining -= focus;
      if (remaining >= brk) {
        schedule.push({ step: step++, type: "break", minutes: brk });
        remaining -= brk;
      } else break;
    }
    const cycles = schedule.filter((s) => s.type === "focus").length;
    const totalFocus = cycles * focus;
    const plan = {
      cycles,
      focus_minutes: focus,
      break_minutes: brk,
      total_focus_minutes: totalFocus,
      leftover_minutes: remaining,
      cycle_length_minutes: cycle,
      schedule
    };
    const text = cycles ? `${cycles} focus session${cycles > 1 ? "s" : ""} of ${focus} min (${totalFocus} min focused), ${brk} min breaks between. ${remaining} min left over.` : `Not enough time for a full ${focus} min focus session.`;
    return { content: [{ type: "text", text }], structuredContent: plan };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vsvptwvawdpikhpecssj";
var mcp_default = defineMcp({
  name: "flowzen",
  title: "FlowZen",
  version: "0.1.0",
  instructions: "Tools for FlowZen, a mindful Pomodoro focus app. Use `get_profile` and `update_display_name` for the signed-in user's profile, `plan_focus_session` to lay out focus/break cycles for a block of time, and `suggest_break_activity` for mindful break ideas.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, update_display_name_default, plan_focus_session_default, suggest_break_activity_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
